### ISSUE TITLE
How to after release

### ISSUE THREAD

**Issue by nohnaimer** [yiisoft/db-pgsql#1]
### What steps will reproduce the problem?
Тип array postgresql возвращается object, сейчас еще есть возможность сказать дай array https://github.com/yiisoft/yii2/blob/1fe3d61a3bac1fb8e59b9d026d9f37b5c5eadd4a/framework/db/pgsql/ColumnSchema.php#L99
### What is the expected result?
Теперь после обновления https://github.com/yiisoft/db-pgsql/blob/3edf67d681271034499a80dc71414c8f9e97881d/src/ColumnSchema.php#L66 всегда object
### What do you get instead?
Нельзя ли оставить возможность выбора, потому что не удобно получать данные. Когда из базы после populate летит object приходится в модели делать getер, задача которого вызывать getValue() и все, хотя лучше просто из базы получить нужный массив с данными... Но может я не прав... В общем как будем жить дальше?

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.16
| PHP version      | 7.2
| Operating system | CentOS 7|macOS Mojave

**Comment by darkdef** [comment]
Works in current implementation.
