### ISSUE TITLE
Make `ArrayParser` internal and prevent multiple create instance of it

### ISSUE THREAD

**Issue by vjik** [yiisoft/db-pgsql#297]
~1) Suggest make `ArrayParser` as internal. Users don't must use this class directly, it'sright?~ (https://github.com/yiisoft/db-pgsql/issues/297#issuecomment-1660221235)

2) For each type casting of string values created new instance of `ArrayParser`.

https://github.com/yiisoft/db-pgsql/blob/56df5ac9907ecc0582d3f4303b711588620a806e/src/ColumnSchema.php#L107-L112

It would be good prevent this behavior and create instance of `ArrayParser` once or make `ArrayParser` methods static.

Similar case: https://github.com/yiisoft/db-pgsql/pull/303#discussion_r1280336415

**Comment by terabytesoftw** [comment]
> 1. Suggest make `ArrayParser` as internal. Users don't must use this class directly, it'sright?
> 2. For each type casting of string values created new instance of `ArrayParser`.
> 
> https://github.com/yiisoft/db-pgsql/blob/56df5ac9907ecc0582d3f4303b711588620a806e/src/ColumnSchema.php#L107-L112
> 
> It would be good prevent this behavior and create instance of `ArrayParser` once or make `ArrayParser` methods static.

`getArrayParser()` return `new ArrayParser()`.

**Comment by vjik** [comment]
> `getArrayParser()` return `new ArrayParser()`.

And creates new instance every time.

**Comment by terabytesoftw** [comment]
> > `getArrayParser()` return `new ArrayParser()`.
> 
> And creates new instance every time.

yes, that's not a problem, it just resolves the value, it's not saved anywhere.

**Comment by vjik** [comment]
> yes, that's not a problem, it just resolves the value, it's not saved anywhere.

Why create instance every time?
Many times - for each type casting.

**Comment by terabytesoftw** [comment]
> > yes, that's not a problem, it just resolves the value, it's not saved anywhere.
> 
> Why create instance every time? Many times - for each type casting.

But that's not a problem, as I tell you the object is not saved, it only resolves the value.

**Comment by terabytesoftw** [comment]
> > > yes, that's not a problem, it just resolves the value, it's not saved anywhere.
> > 
> > 
> > Why create instance every time? Many times - for each type casting.
> 
> But that's not a problem, as i tell you the object is not saved, it only resolves the value.

It's like widgets, they always create an object, and resolve its value to a string.

**Comment by samdark** [comment]
Should be a good optimization. Worth benchmarking.

**Comment by terabytesoftw** [comment]
Btw array parser cannot be internal, `Db` is an abstraction and you may need it for an extension.

**Comment by vjik** [comment]
> Btw array parser cannot be internal, `Db` is an abstraction and you may need it for an extension.

`ArrayParser` used in specific implementation for PostgreSQL. When might it be needed somewhere else?

**Comment by terabytesoftw** [comment]
Simple, if I create my own `db-pgsql` implementation, or just create the `PGSQL NON-PDO` implementation, for example.

**Comment by vjik** [comment]
> Simple, if I create my own `db-pgsql` implementation, or just create the `PGSQL NON-PDO` implementation, for example.
> 
> Everything cannot be within the framework, there will be extensions.

It's will be extension of `yiisoft/db`, not `yiisoft/db-pgsql`. Array parser is not goal of this package, I don't think that `yiisoft/db-pgsql` should provide it.

**Comment by Tigrov** [comment]
The parser can potentially be used for in-project optimization.

For example:
```php
$intArray = $command->setSql('SELECT int_array FROM some_table')->queryScalar();
$parsedArray = (new ArrayParser())->parse($intArray);
$castArray = array_map('intval', $parsedArray);
```

instead of `$castArray = $column->phpTypecast($intArray)`.

**Comment by vjik** [comment]
> instead of `$castArray = $column->phpTypecast($intArray)`.

Agree. This is good case.

**Comment by smirnov-e** [comment]
> can potentially be used for in-project optimization.

It's not optimisation, but the only way to get array from raw responses :(

**Comment by Tigrov** [comment]
> It's not optimisation, but the only way to get array from raw responses :(

There is the second way where the parser is not used directly:
```php
$castArray = $column->phpTypecast($rawIntArray);
```

But the first way will work almost 2 times faster.

**Comment by Tigrov** [comment]
Benchmarks to compare current implementation with using property or static class:

https://github.com/Tigrov/yii3-benchmarks/blob/master/src/Benchmark/PgsqlBench.php

Results:
```
    benchParseIntArrayCurrent...............I4 - Mo367.103μs (±0.61%)
    benchParseIntArrayProperty..............I4 - Mo367.761μs (±0.90%)
    benchParseIntArrayVar...................I4 - Mo369.223μs (±0.29%)
    benchParseIntArrayNew...................I4 - Mo385.663μs (±0.31%)
    benchParseIntArrayStatic................I4 - Mo372.307μs (±0.36%)
```

**Comment by vjik** [comment]
> Benchmarks to compare current implementation with using property or static class:

Optimization in PHP good work.

Seems, for cases when object use clear methods without side effects we can create object many times and it don't degradate performance.

**Comment by smirnov-e** [comment]
@vjik `benchParseIntArrayNew` is 4.8% slower than `benchParseIntArrayProperty`. Difference is not big, but noticeable.

**Comment by vjik** [comment]
> @vjik `benchParseIntArrayNew` is 4.8% slower than `benchParseIntArrayProperty`. Difference is not big, but noticeable.

On my PC result little other:

![image](https://github.com/yiisoft/db-pgsql/assets/525501/f596072c-12ba-47bd-b4b6-d01d9b6c70a7)

Difference is so small.

**Comment by Tigrov** [comment]
Changed ITEMS_COUNT to 1, results a slightly different:

```
    benchParseIntArrayCurrent...............I4 - Mo0.825μs (±1.67%)
    benchParseIntArrayProperty..............I4 - Mo0.765μs (±1.31%)
    benchParseIntArrayVar...................R5 I4 - Mo0.793μs (±1.83%)
    benchParseIntArrayNew...................R1 I3 - Mo0.790μs (±1.25%)
    benchParseIntArrayStatic................R1 I4 - Mo0.982μs (±1.52%)
```

Looks with property works faster but the benchmark doesn't cover initialization of the property (from constructor, method or cache)

**Comment by vjik** [comment]
Difference is so small and in different environments results may vary slightly. By logic property and static should be most performance, but in optimization most logic not always is most performance.

@Tigrov Little improve benchmark: https://github.com/Tigrov/yii3-benchmarks/pull/1

My results:

![image](https://github.com/yiisoft/db-pgsql/assets/525501/421dbcd8-2383-4d6b-94e8-4625af4fd254)

Looks like directly use `new`  (`(new ArrayHelper())->parse()`) is most performance variant.
