### ISSUE TITLE
Prevent auto increment of primary key on duplicate values when `upsert()`

### ISSUE THREAD

**Issue by Tigrov** [yiisoft/db-pgsql#317]
When attempting to `upsert()` duplicate values the autoincrement primary key will be incremented even if no duplicates are inserted.
```php
$columns = ['unique_field' => 'unique value', 'field' => 'value'];
$command->upsert('table_name', $columns, false)->execute();
```

Generated query:
```sql
INSERT INTO table_name (unique_field, field) VALUES ('unique value', 'value') ON CONFLICT DO NOTHING
```

This can be solved by generating query without `ON CONFLICT DO NOTHING`

```sql
INSERT INTO table_name (unique_field, field)
SELECT 'unique value', 'value'
WHERE NOT EXISTS(
    SELECT 1
    FROM table_name
    WHERE unique_field = 'unique value'
)
```

| Q                | A
| ---------------- | ---
| Version          | 1.1.0

**Comment by vjik** [comment]
Hm. For implement this logic need analyze table schema (via lookup unique indexes?), right?

**Comment by Tigrov** [comment]
> Hm. For implement this logic need analyze table schema (via lookup unique indexes?), right?

Yes, the method already do this:

https://github.com/yiisoft/db-pgsql/blob/cf03e81c4e726fb127e2a365d9987ee7d962aa70/src/DMLQueryBuilder.php#L72

For solving the issue need to generate another query, and compare benchmarks.

**Comment by Tigrov** [comment]
The suggested solution slower on 10% if no unique values found and 5% faster if unique values found
