### ISSUE TITLE
Wrong SQL with not unique index type

### ISSUE THREAD

**Issue by Gerych1984** [yiisoft/db-pgsql#320]
Good day. In [](https://github.com/yiisoft/db-pgsql/blob/c46707095eacdadc4589f9d729ddb1a6484464a4/src/DDLQueryBuilder.php#L114) in case when create GIN/GIST other not unique index asresult we have wrong SQL query. For example in migration:

```
$b->createIndex('name', 'table', 'column', 'GIN');

CREATE GIN INDEX 'name' ON 'table' USING GIN ('column') //wrong GIN after CREATE

```

**Comment by Tigrov** [comment]
The index method (GIN) must be the 5th parameter.

Try this
```sql
$b->createIndex('name', 'table', 'column', null, 'GIN');
```

**Comment by Gerych1984** [comment]
> The index method (GIN) should be the 5th parameter.
> 
> Try this
> 
> ```sql
> $b->createIndex('name', 'table', 'column', null, 'GIN');
> ```
My mistake, it's time to go on vacation )
