### ISSUE TITLE
May be need add compatible result for phptypes?

### ISSUE THREAD

**Issue by darkdef** [yiisoft/db-pgsql#87]
See - https://github.com/yiisoft/db-pgsql/blob/3d47b9af600c807b981d25406ad7a02abac98ab7/src/ColumnSchema.php#L81
```php
if ($this->dimension > 0) {
            if (!is_array($value)) {
                $value = $this->getArrayParser()->parse($value);
            }
...
```

After change DB from pgsql to mysql - we can't will use class ArrayParser (and other pgsql specified types from this package) in our application

if ($value instanceof ArrayParser) - will be throws Exception

**Comment by Tigrov** [comment]
If use `array` or another specific type such as `composite`, type casting should be used to get the correct result in `PHP`.
When converting to another DBMS, it must be converted to a compatible type, for example `json` for `MySQL`.
Then in the new DBMS it can be used as a correct type.
